// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_bkk_api.Models;

namespace Project_bkk_api.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("25620722094439_Migration-0002")]
    partial class Migration0002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Project_bkk_api.Models.Test.Test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("age")
                        .HasColumnType("int(3)");

                    b.Property<string>("fullname")
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("test");
                });
#pragma warning restore 612, 618
        }
    }
}
